import type { CreateShortenURLAJAXRequest } from "type/api";
import { ajax } from "util/network";
// Attention: This file is generated by "yarn api", do not modify

export class V1AJAXService {
  static getHash(hash: string): Promise<void> {
    return ajax("GET", "/v1/:hash", { hash }, null);
  }

  static createShortURL(request: CreateShortenURLAJAXRequest): Promise<string> {
    return ajax("POST", "/v1/", {}, request);
  }
}
